### ISSUE TITLE
Words with hashtags (#) at the beginning are overlapping 

### ISSUE THREAD

**Issue by Harpush** [jasondavies/d3-cloud#190] opened 2024-06-20 12:09 UTC
With words having ltr ot rtl language with hashtag (`#`) at the beginning the words sometimes overlap

**Comment by jasondavies** [comment] 2024-06-20 12:20
Can you provide a reproducible example?

**Comment by Harpush** [comment] 2024-06-21 09:46
> Can you provide a reproducible example?

@jasondavies Hey here is an example (hashtags English and Arabic mixed words):
https://codepen.io/Harpush/pen/QWRmaZR

**Comment by jasondavies** [comment] 2024-06-21 10:35
Works fine for me in Chrome.

<img width="717" alt="Screenshot 2024-06-21 at 11 34 53" src="https://github.com/jasondavies/d3-cloud/assets/31223/c0704146-b426-4b42-a816-c5bb221705c8">

**Comment by Harpush** [comment] 2024-06-21 10:48
@jasondavies That's weird... Here is mine:
![image](https://github.com/jasondavies/d3-cloud/assets/30085989/cf60dc99-69b7-4e55-b914-6d5ad26f19ec)
On chrome Version 125.0.6422.142 (Official Build) (64-bit)
Windows 10

**Comment by Harpush** [comment] 2024-06-21 10:50
Interesting this seems to look much better at chrome 126:
![image](https://github.com/jasondavies/d3-cloud/assets/30085989/0807d471-61cd-452f-b014-486500ea2269)
Although not everyone moved to the new chrome :(

**Comment by jasondavies** [comment] 2024-06-21 11:09
Looks like your example is also using an old version of d3-cloud (1.2.5).  Maybe try 1.2.7 as it includes a workaround for a known issue with RTL text measurement and alignment in Chrome.

**Comment by jasondavies** [comment] 2024-06-21 13:03
I checked on Chrome 125 on Windows 10 and reproduced the issue with d3-cloud@1.2.5, but it's fixed by d3-cloud@1.2.7.

**Closed by jasondavies** 2024-06-21 13:03 UTC

**Comment by Harpush** [comment] 2024-06-21 13:21
@jasondavies I will try and see if I can reproduce with 1.2.7 as I am pretty sure the problematic project is updated to 1.2.7. if I can reproduce I will open a new issue
