### ISSUE TITLE
long 'words'?

### ISSUE THREAD

**Issue by ignacio82** [jasondavies/d3-cloud#74] opened 2015-08-28 13:37 UTC
I'm trying to generate a wordcloud using [d3wordcloud](https://github.com/jbkunst/d3wordcloud/issues/8#issuecomment-135775500) and some of the words are not plotted. Is this a bug in `d3-cloud`?

Thanks!

**Comment by jasondavies** [comment] 2015-09-24 22:18
Duplicate of #36.  It’s a known problem when words are too large to fit: they get dropped at the moment.

**Closed by jasondavies** 2015-09-24 22:18 UTC
